const Web3 = require('web3');
const contractABI = require('../path_to_your_compiled_contract_ABI.json'); // the ABI generated by Hardhat
const contractAddress = 'deployed_contract_address_here'; // address returned by the deployment script

const web3 = new Web3('https://sepolia.infura.io/v3/your_infura_project_id');
const contract = new web3.eth.Contract(contractABI, contractAddress);

async function requestRandomUsers() {
    const accounts = await web3.eth.getAccounts(); // Assuming you're managing keys/accounts elsewhere
    return contract.methods.requestRandomUsers().send({ from: accounts[0] });
}

async function getAssignedUsers(requestId) {
    return contract.methods.getAssignedUsers(requestId).call();
}

module.exports = {
    requestRandomUsers,
    getAssignedUsers
};
