/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssignGroup_old: typeof import('./src/components/AssignGroup_old.vue')['default']
    Debug: typeof import('./src/components/Debug.vue')['default']
    GroupDisplay: typeof import('./src/components/GroupDisplay.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Inbox: typeof import('./src/components/Inbox.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    Providers: typeof import('./src/components/Providers.vue')['default']
    RandomNumber: typeof import('./src/components/RandomNumber.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendMessage: typeof import('./src/components/SendMessage.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
